/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-05-05 07:46:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<link\r\n");
      out.write("		href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\"\r\n");
      out.write("		rel=\"stylesheet\"\r\n");
      out.write("		integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\"\r\n");
      out.write("		crossorigin=\"anonymous\" />\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/myStyle.css\" />\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE\"\r\n");
      out.write("		crossorigin=\"anonymous\">\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ\"\r\n");
      out.write("		crossorigin=\"anonymous\">\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	<title>Register/Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<section class=\"vh-100\">\r\n");
      out.write("		<div class=\"container-fluid h-custom\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("				<div class=\"col-md-9 col-lg-6 col-xl-5\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp\"\r\n");
      out.write("						class=\"img-fluid\" alt=\"Sample image\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-8 col-lg-6 col-xl-4 offset-xl-1\">\r\n");
      out.write("					<form action=\"register\" method=\"GET\">\r\n");
      out.write("						<h1 class=\"py-4 text-primary\">Đăng ký</h1>\r\n");
      out.write("						<!-- Usernmae input -->\r\n");
      out.write("						<div class=\"form-outline mb-4\">\r\n");
      out.write("							<label class=\"form-label\" for=\"username\">Tên đăng nhập</label> <input\r\n");
      out.write("								type=\"text\" id=\"username\" class=\"form-control form-control-lg\"\r\n");
      out.write("								placeholder=\"Nhập tên đăng nhập\" name=\"username\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Email input -->\r\n");
      out.write("						<div class=\"form-outline mb-4\">\r\n");
      out.write("							<label class=\"form-label\" for=\"email\">Email</label> <input\r\n");
      out.write("								type=\"email\" id=\"email\" class=\"form-control form-control-lg\"\r\n");
      out.write("								placeholder=\"Nhập địa chỉ email\" name=\"email\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Password input -->\r\n");
      out.write("						<div class=\"form-outline mb-3\">\r\n");
      out.write("							<label class=\"form-label\" for=\"password\">Mật khẩu</label> <input\r\n");
      out.write("								type=\"password\" id=\"password\"\r\n");
      out.write("								class=\"form-control form-control-lg\" placeholder=\"Nhập mật khẩu\"\r\n");
      out.write("								name=\"password\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("							<!-- Checkbox -->\r\n");
      out.write("							<div class=\"form-check mb-0\">\r\n");
      out.write("								<input class=\"form-check-input me-2\" type=\"checkbox\" value=\"\"\r\n");
      out.write("									id=\"form2Example3\" /> <label class=\"form-check-label\"\r\n");
      out.write("									for=\"form2Example3\"> Đồng ý với các điều khoản </label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a href=\"#!\" class=\"text-body\">Quên mật khẩu?</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"text-center text-lg-start mt-4 pt-2\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary btn-lg\"\r\n");
      out.write("								style=\"padding-left: 2.5rem; padding-right: 2.5rem;\">Đăng\r\n");
      out.write("								ký</button>\r\n");
      out.write("							<p class=\"small fw-bold mt-2 pt-1 mb-0\">\r\n");
      out.write("								Đã có tài khoản? <a href=\"login.jsp\" class=\"link-danger\">Đăng\r\n");
      out.write("									nhập</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
